// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/netflix.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Movie         string                 `protobuf:"bytes,2,opt,name=movie,proto3" json:"movie,omitempty"`
	Watched       bool                   `protobuf:"varint,3,opt,name=watched,proto3" json:"watched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_proto_netflix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netflix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_proto_netflix_proto_rawDescGZIP(), []int{0}
}

func (x *Movie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Movie) GetMovie() string {
	if x != nil {
		return x.Movie
	}
	return ""
}

func (x *Movie) GetWatched() bool {
	if x != nil {
		return x.Watched
	}
	return false
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_proto_netflix_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netflix_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_proto_netflix_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MovieList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Movie               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieList) Reset() {
	*x = MovieList{}
	mi := &file_proto_netflix_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieList) ProtoMessage() {}

func (x *MovieList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netflix_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieList.ProtoReflect.Descriptor instead.
func (*MovieList) Descriptor() ([]byte, []int) {
	return file_proto_netflix_proto_rawDescGZIP(), []int{2}
}

func (x *MovieList) GetList() []*Movie {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateMoive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMoive) Reset() {
	*x = UpdateMoive{}
	mi := &file_proto_netflix_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMoive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMoive) ProtoMessage() {}

func (x *UpdateMoive) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netflix_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMoive.ProtoReflect.Descriptor instead.
func (*UpdateMoive) Descriptor() ([]byte, []int) {
	return file_proto_netflix_proto_rawDescGZIP(), []int{3}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_netflix_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netflix_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_netflix_proto_rawDescGZIP(), []int{4}
}

var File_proto_netflix_proto protoreflect.FileDescriptor

const file_proto_netflix_proto_rawDesc = "" +
	"\n" +
	"\x13proto/netflix.proto\"G\n" +
	"\x05Movie\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05movie\x18\x02 \x01(\tR\x05movie\x12\x18\n" +
	"\awatched\x18\x03 \x01(\bR\awatched\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\tMovieList\x12\x1a\n" +
	"\x04list\x18\x01 \x03(\v2\x06.MovieR\x04list\"\r\n" +
	"\vUpdateMoive\"\a\n" +
	"\x05Empty2\xab\x01\n" +
	"\aNetflix\x12\x1d\n" +
	"\vcreateMovie\x12\x06.Movie\x1a\x06.Movie\x12\"\n" +
	"\fgetAllMovies\x12\x06.Empty\x1a\n" +
	".MovieList\x12\x1a\n" +
	"\vgetMoveById\x12\x03.Id\x1a\x06.Movie\x12!\n" +
	"\x0fupdateMovieById\x12\x06.Movie\x1a\x06.Movie\x12\x1e\n" +
	"\x0fdeleteMovieById\x12\x03.Id\x1a\x06.EmptyB\bZ\x06/protob\x06proto3"

var (
	file_proto_netflix_proto_rawDescOnce sync.Once
	file_proto_netflix_proto_rawDescData []byte
)

func file_proto_netflix_proto_rawDescGZIP() []byte {
	file_proto_netflix_proto_rawDescOnce.Do(func() {
		file_proto_netflix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_netflix_proto_rawDesc), len(file_proto_netflix_proto_rawDesc)))
	})
	return file_proto_netflix_proto_rawDescData
}

var file_proto_netflix_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_netflix_proto_goTypes = []any{
	(*Movie)(nil),       // 0: Movie
	(*Id)(nil),          // 1: Id
	(*MovieList)(nil),   // 2: MovieList
	(*UpdateMoive)(nil), // 3: UpdateMoive
	(*Empty)(nil),       // 4: Empty
}
var file_proto_netflix_proto_depIdxs = []int32{
	0, // 0: MovieList.list:type_name -> Movie
	0, // 1: Netflix.createMovie:input_type -> Movie
	4, // 2: Netflix.getAllMovies:input_type -> Empty
	1, // 3: Netflix.getMoveById:input_type -> Id
	0, // 4: Netflix.updateMovieById:input_type -> Movie
	1, // 5: Netflix.deleteMovieById:input_type -> Id
	0, // 6: Netflix.createMovie:output_type -> Movie
	2, // 7: Netflix.getAllMovies:output_type -> MovieList
	0, // 8: Netflix.getMoveById:output_type -> Movie
	0, // 9: Netflix.updateMovieById:output_type -> Movie
	4, // 10: Netflix.deleteMovieById:output_type -> Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_netflix_proto_init() }
func file_proto_netflix_proto_init() {
	if File_proto_netflix_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_netflix_proto_rawDesc), len(file_proto_netflix_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_netflix_proto_goTypes,
		DependencyIndexes: file_proto_netflix_proto_depIdxs,
		MessageInfos:      file_proto_netflix_proto_msgTypes,
	}.Build()
	File_proto_netflix_proto = out.File
	file_proto_netflix_proto_goTypes = nil
	file_proto_netflix_proto_depIdxs = nil
}
