// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/netflix.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Netflix_CreateMovie_FullMethodName     = "/Netflix/createMovie"
	Netflix_GetAllMovies_FullMethodName    = "/Netflix/getAllMovies"
	Netflix_GetMoveById_FullMethodName     = "/Netflix/getMoveById"
	Netflix_UpdateMovieById_FullMethodName = "/Netflix/updateMovieById"
	Netflix_DeleteMovieById_FullMethodName = "/Netflix/deleteMovieById"
)

// NetflixClient is the client API for Netflix service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetflixClient interface {
	CreateMovie(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Movie, error)
	GetAllMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MovieList, error)
	GetMoveById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Movie, error)
	UpdateMovieById(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Movie, error)
	DeleteMovieById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error)
}

type netflixClient struct {
	cc grpc.ClientConnInterface
}

func NewNetflixClient(cc grpc.ClientConnInterface) NetflixClient {
	return &netflixClient{cc}
}

func (c *netflixClient) CreateMovie(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Movie, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Movie)
	err := c.cc.Invoke(ctx, Netflix_CreateMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netflixClient) GetAllMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MovieList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MovieList)
	err := c.cc.Invoke(ctx, Netflix_GetAllMovies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netflixClient) GetMoveById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Movie, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Movie)
	err := c.cc.Invoke(ctx, Netflix_GetMoveById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netflixClient) UpdateMovieById(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Movie, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Movie)
	err := c.cc.Invoke(ctx, Netflix_UpdateMovieById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netflixClient) DeleteMovieById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Netflix_DeleteMovieById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetflixServer is the server API for Netflix service.
// All implementations must embed UnimplementedNetflixServer
// for forward compatibility.
type NetflixServer interface {
	CreateMovie(context.Context, *Movie) (*Movie, error)
	GetAllMovies(context.Context, *Empty) (*MovieList, error)
	GetMoveById(context.Context, *Id) (*Movie, error)
	UpdateMovieById(context.Context, *Movie) (*Movie, error)
	DeleteMovieById(context.Context, *Id) (*Empty, error)
	mustEmbedUnimplementedNetflixServer()
}

// UnimplementedNetflixServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetflixServer struct{}

func (UnimplementedNetflixServer) CreateMovie(context.Context, *Movie) (*Movie, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMovie not implemented")
}
func (UnimplementedNetflixServer) GetAllMovies(context.Context, *Empty) (*MovieList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllMovies not implemented")
}
func (UnimplementedNetflixServer) GetMoveById(context.Context, *Id) (*Movie, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMoveById not implemented")
}
func (UnimplementedNetflixServer) UpdateMovieById(context.Context, *Movie) (*Movie, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMovieById not implemented")
}
func (UnimplementedNetflixServer) DeleteMovieById(context.Context, *Id) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMovieById not implemented")
}
func (UnimplementedNetflixServer) mustEmbedUnimplementedNetflixServer() {}
func (UnimplementedNetflixServer) testEmbeddedByValue()                 {}

// UnsafeNetflixServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetflixServer will
// result in compilation errors.
type UnsafeNetflixServer interface {
	mustEmbedUnimplementedNetflixServer()
}

func RegisterNetflixServer(s grpc.ServiceRegistrar, srv NetflixServer) {
	// If the following call panics, it indicates UnimplementedNetflixServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Netflix_ServiceDesc, srv)
}

func _Netflix_CreateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Movie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetflixServer).CreateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netflix_CreateMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetflixServer).CreateMovie(ctx, req.(*Movie))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netflix_GetAllMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetflixServer).GetAllMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netflix_GetAllMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetflixServer).GetAllMovies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netflix_GetMoveById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetflixServer).GetMoveById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netflix_GetMoveById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetflixServer).GetMoveById(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netflix_UpdateMovieById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Movie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetflixServer).UpdateMovieById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netflix_UpdateMovieById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetflixServer).UpdateMovieById(ctx, req.(*Movie))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netflix_DeleteMovieById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetflixServer).DeleteMovieById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netflix_DeleteMovieById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetflixServer).DeleteMovieById(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

// Netflix_ServiceDesc is the grpc.ServiceDesc for Netflix service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Netflix_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Netflix",
	HandlerType: (*NetflixServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createMovie",
			Handler:    _Netflix_CreateMovie_Handler,
		},
		{
			MethodName: "getAllMovies",
			Handler:    _Netflix_GetAllMovies_Handler,
		},
		{
			MethodName: "getMoveById",
			Handler:    _Netflix_GetMoveById_Handler,
		},
		{
			MethodName: "updateMovieById",
			Handler:    _Netflix_UpdateMovieById_Handler,
		},
		{
			MethodName: "deleteMovieById",
			Handler:    _Netflix_DeleteMovieById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/netflix.proto",
}
