// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/netflix.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MovieService_CreateMovie_FullMethodName   = "/proto.MovieService/CreateMovie"
	MovieService_GetAllMovies_FullMethodName  = "/proto.MovieService/GetAllMovies"
	MovieService_UpdateWatched_FullMethodName = "/proto.MovieService/UpdateWatched"
	MovieService_DeleteMovie_FullMethodName   = "/proto.MovieService/DeleteMovie"
)

// MovieServiceClient is the client API for MovieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieServiceClient interface {
	CreateMovie(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Movie, error)
	GetAllMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MovieList, error)
	UpdateWatched(ctx context.Context, in *MovieId, opts ...grpc.CallOption) (*Movie, error)
	DeleteMovie(ctx context.Context, in *MovieId, opts ...grpc.CallOption) (*Empty, error)
}

type movieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieServiceClient(cc grpc.ClientConnInterface) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) CreateMovie(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Movie, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Movie)
	err := c.cc.Invoke(ctx, MovieService_CreateMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) GetAllMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MovieList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MovieList)
	err := c.cc.Invoke(ctx, MovieService_GetAllMovies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) UpdateWatched(ctx context.Context, in *MovieId, opts ...grpc.CallOption) (*Movie, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Movie)
	err := c.cc.Invoke(ctx, MovieService_UpdateWatched_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) DeleteMovie(ctx context.Context, in *MovieId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MovieService_DeleteMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServiceServer is the server API for MovieService service.
// All implementations must embed UnimplementedMovieServiceServer
// for forward compatibility.
type MovieServiceServer interface {
	CreateMovie(context.Context, *Movie) (*Movie, error)
	GetAllMovies(context.Context, *Empty) (*MovieList, error)
	UpdateWatched(context.Context, *MovieId) (*Movie, error)
	DeleteMovie(context.Context, *MovieId) (*Empty, error)
	mustEmbedUnimplementedMovieServiceServer()
}

// UnimplementedMovieServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMovieServiceServer struct{}

func (UnimplementedMovieServiceServer) CreateMovie(context.Context, *Movie) (*Movie, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMovie not implemented")
}
func (UnimplementedMovieServiceServer) GetAllMovies(context.Context, *Empty) (*MovieList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllMovies not implemented")
}
func (UnimplementedMovieServiceServer) UpdateWatched(context.Context, *MovieId) (*Movie, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWatched not implemented")
}
func (UnimplementedMovieServiceServer) DeleteMovie(context.Context, *MovieId) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMovie not implemented")
}
func (UnimplementedMovieServiceServer) mustEmbedUnimplementedMovieServiceServer() {}
func (UnimplementedMovieServiceServer) testEmbeddedByValue()                      {}

// UnsafeMovieServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieServiceServer will
// result in compilation errors.
type UnsafeMovieServiceServer interface {
	mustEmbedUnimplementedMovieServiceServer()
}

func RegisterMovieServiceServer(s grpc.ServiceRegistrar, srv MovieServiceServer) {
	// If the following call panics, it indicates UnimplementedMovieServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MovieService_ServiceDesc, srv)
}

func _MovieService_CreateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Movie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).CreateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieService_CreateMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).CreateMovie(ctx, req.(*Movie))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_GetAllMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).GetAllMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieService_GetAllMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).GetAllMovies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_UpdateWatched_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).UpdateWatched(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieService_UpdateWatched_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).UpdateWatched(ctx, req.(*MovieId))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_DeleteMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).DeleteMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieService_DeleteMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).DeleteMovie(ctx, req.(*MovieId))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieService_ServiceDesc is the grpc.ServiceDesc for MovieService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MovieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMovie",
			Handler:    _MovieService_CreateMovie_Handler,
		},
		{
			MethodName: "GetAllMovies",
			Handler:    _MovieService_GetAllMovies_Handler,
		},
		{
			MethodName: "UpdateWatched",
			Handler:    _MovieService_UpdateWatched_Handler,
		},
		{
			MethodName: "DeleteMovie",
			Handler:    _MovieService_DeleteMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/netflix.proto",
}

const (
	SeriesService_CreateSeries_FullMethodName  = "/proto.SeriesService/CreateSeries"
	SeriesService_GetAllSeries_FullMethodName  = "/proto.SeriesService/GetAllSeries"
	SeriesService_UpdateWatched_FullMethodName = "/proto.SeriesService/UpdateWatched"
	SeriesService_DeleteSeries_FullMethodName  = "/proto.SeriesService/DeleteSeries"
)

// SeriesServiceClient is the client API for SeriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeriesServiceClient interface {
	CreateSeries(ctx context.Context, in *Series, opts ...grpc.CallOption) (*Series, error)
	GetAllSeries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SeriesList, error)
	UpdateWatched(ctx context.Context, in *SeriesId, opts ...grpc.CallOption) (*Series, error)
	DeleteSeries(ctx context.Context, in *SeriesId, opts ...grpc.CallOption) (*Empty, error)
}

type seriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeriesServiceClient(cc grpc.ClientConnInterface) SeriesServiceClient {
	return &seriesServiceClient{cc}
}

func (c *seriesServiceClient) CreateSeries(ctx context.Context, in *Series, opts ...grpc.CallOption) (*Series, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Series)
	err := c.cc.Invoke(ctx, SeriesService_CreateSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seriesServiceClient) GetAllSeries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SeriesList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeriesList)
	err := c.cc.Invoke(ctx, SeriesService_GetAllSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seriesServiceClient) UpdateWatched(ctx context.Context, in *SeriesId, opts ...grpc.CallOption) (*Series, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Series)
	err := c.cc.Invoke(ctx, SeriesService_UpdateWatched_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seriesServiceClient) DeleteSeries(ctx context.Context, in *SeriesId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SeriesService_DeleteSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeriesServiceServer is the server API for SeriesService service.
// All implementations must embed UnimplementedSeriesServiceServer
// for forward compatibility.
type SeriesServiceServer interface {
	CreateSeries(context.Context, *Series) (*Series, error)
	GetAllSeries(context.Context, *Empty) (*SeriesList, error)
	UpdateWatched(context.Context, *SeriesId) (*Series, error)
	DeleteSeries(context.Context, *SeriesId) (*Empty, error)
	mustEmbedUnimplementedSeriesServiceServer()
}

// UnimplementedSeriesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeriesServiceServer struct{}

func (UnimplementedSeriesServiceServer) CreateSeries(context.Context, *Series) (*Series, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSeries not implemented")
}
func (UnimplementedSeriesServiceServer) GetAllSeries(context.Context, *Empty) (*SeriesList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSeries not implemented")
}
func (UnimplementedSeriesServiceServer) UpdateWatched(context.Context, *SeriesId) (*Series, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWatched not implemented")
}
func (UnimplementedSeriesServiceServer) DeleteSeries(context.Context, *SeriesId) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSeries not implemented")
}
func (UnimplementedSeriesServiceServer) mustEmbedUnimplementedSeriesServiceServer() {}
func (UnimplementedSeriesServiceServer) testEmbeddedByValue()                       {}

// UnsafeSeriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeriesServiceServer will
// result in compilation errors.
type UnsafeSeriesServiceServer interface {
	mustEmbedUnimplementedSeriesServiceServer()
}

func RegisterSeriesServiceServer(s grpc.ServiceRegistrar, srv SeriesServiceServer) {
	// If the following call panics, it indicates UnimplementedSeriesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeriesService_ServiceDesc, srv)
}

func _SeriesService_CreateSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Series)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeriesServiceServer).CreateSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeriesService_CreateSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeriesServiceServer).CreateSeries(ctx, req.(*Series))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeriesService_GetAllSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeriesServiceServer).GetAllSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeriesService_GetAllSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeriesServiceServer).GetAllSeries(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeriesService_UpdateWatched_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeriesId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeriesServiceServer).UpdateWatched(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeriesService_UpdateWatched_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeriesServiceServer).UpdateWatched(ctx, req.(*SeriesId))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeriesService_DeleteSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeriesId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeriesServiceServer).DeleteSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeriesService_DeleteSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeriesServiceServer).DeleteSeries(ctx, req.(*SeriesId))
	}
	return interceptor(ctx, in, info, handler)
}

// SeriesService_ServiceDesc is the grpc.ServiceDesc for SeriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SeriesService",
	HandlerType: (*SeriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSeries",
			Handler:    _SeriesService_CreateSeries_Handler,
		},
		{
			MethodName: "GetAllSeries",
			Handler:    _SeriesService_GetAllSeries_Handler,
		},
		{
			MethodName: "UpdateWatched",
			Handler:    _SeriesService_UpdateWatched_Handler,
		},
		{
			MethodName: "DeleteSeries",
			Handler:    _SeriesService_DeleteSeries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/netflix.proto",
}
